--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admins (
    id character varying(50) NOT NULL,
    created_at timestamp(6) without time zone,
    enabled boolean NOT NULL,
    name character varying(100) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.admins OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    enabled boolean NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: admins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admins (id, created_at, enabled, name, password) FROM stdin;
001	2025-09-02 09:48:45.69032	t	Uma	$2a$10$1f4nfdMJJl3I5P.2GejT4OZ3aEhMNj0z48zhuAnS7nmBCxAJ25v2m
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, enabled, name, password, phone) FROM stdin;
2	2025-09-02 09:50:59.718739	t	New User	$2a$10$ORzUdShk8DkHuAOlJ9/HDuXqCCNwKJKWbPsm2yFO9lSx6d2uG3KyW	0987654321
3	\N	t	akshitha	$2a$10$HyYxethd0TDdkuFtU9Vqg.CW/Xy42DnQ6YhVA1.QvB8dnh8pz2Gxu	9012345678
1	2025-09-02 09:50:59.718739	t	Uma	$2a$10$uC6nyGoI0zvhGGtqVnVs7uP9RUXrYIjgxK6IuMxMco5Uo11tMyjXa	9344211325
4	\N	t	sirusti	$2a$10$GKLlhERtbadJ8hCLgcn7EOx9l2pyID0yNQVXs76Ok4FGVlGBBju0W	6381799907
\.


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id);


--
-- Name: users ukdu5v5sr43g5bfnji4vb8hg5s3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukdu5v5sr43g5bfnji4vb8hg5s3 UNIQUE (phone);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

